version: "3.9"

services:
  nginx:
    container_name: sabaidea-task-nginx
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  php:
    container_name: sabaidea-task-php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/html

  mysql:
    container_name: sabaidea-task-mysql
    image: mysql:latest
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
